version: '3.8'

services:
  campus_postgres:
    image: postgres:latest
    container_name: campus_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: campus
      POSTGRES_PASSWORD: campus
      POSTGRES_DB: campus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - campus

  campus_back:
    build:
      context: ./back
    container_name: campus_back
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://campus_postgres:5432/campus_db
      POSTGRES_USER: campus
      POSTGRES_PASSWORD: campus
    ports:
      - "8080:8080"
    networks:
      - campus
    depends_on:
      - campus_postgres

  campus_front:
    build:
      context: ./front
    container_name: campus_front
    ports:
      - "3000:3000"
    networks:
      - campus

volumes:
  postgres_data:


networks:
  campus:
    driver: bridge
