version: '3.8'

services:
  campus-postgres:
    image: postgres:latest
    container_name: campus-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: campus
      POSTGRES_PASSWORD: campus
      POSTGRES_DB: campus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - campus

  campus-back:
    build:
      context: ./back
    container_name: campus-back
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://campus-postgres:5432/campus_db
      SPRING_DATASOURCE_USERNAME: campus
      SPRING_DATASOURCE_PASSWORD: campus
    ports:
      - "8080:8080"
    networks:
      - campus
    depends_on:
      - campus-postgres

  campus-front:
    build:
      context: ./front
      args:
        - PUBLIC_API_BASE_URL=http://campus-back:8080/api
    container_name: campus-front
    environment:
      - ORIGIN=http://localhost:5173
      - PUBLIC_API_BASE_URL=http://campus-back:8080/api
    ports:
      - "5173:3000"
    networks:
      - campus

volumes:
  postgres_data:


networks:
  campus:
    driver: bridge
